language: bash

sudo: required

services:
  - docker

env:
  - VERSION=5.3
  - VERSION=5.4
  - VERSION=5.5
  - VERSION=5.6
  - VERSION=7.0

before_script:
  - env | sort

script:
  - ./build.sh $VERSION
  - docker run -it jakzal/symfony-dev:$VERSION php -v

after_script:
  - docker images
