language: bash

sudo: required

services:
  - docker

env:
  - VERSION=5.3
  - VERSION=5.4
  - VERSION=5.5
  - VERSION=5.6
  - VERSION=7.0

before_script:
  - env | sort

script:
  - ./build.sh $VERSION
  - docker run -it jakzal/symfony-dev:$VERSION php -v
  - docker run -it jakzal/symfony-dev:$VERSION php -m | grep intl
  - if [ "$VERSION" != "7.0" ]; then docker run -it jakzal/symfony-dev:$VERSION php -m | grep xdebug; fi
  - if [ "$VERSION" != "7.0" ]; then docker run -it jakzal/symfony-dev:$VERSION php -m | grep -E 'memcache\W'; fi
  - if [ "$VERSION" != "7.0" ]; then docker run -it jakzal/symfony-dev:$VERSION php -m | grep memcached; fi

after_script:
  - docker images
